modLoader = "kotlinforforge"
loaderVersion = "[6,)"
license = "GPL-3.0"

[[mods]]
modId = "sinisterdiscs"
version = "1.2.0"
displayName = "Sinister Discs"
logoFile="sinisterdiscs.png"
credits="TODO"
authors = "basil_squared"
description = '''Adds music discs from the Sinister Minds album.'''




[[dependencies. sinisterdiscs]]
modId = "neoforge"
type="required"
versionRange = "[21.11.3-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sinisterdiscs]]
modId = "minecraft"
type="required"
versionRange = "[1.21.11, 1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sinisterdiscs]]
modId = "kotlinforforge"
type="required"
versionRange = "[6,)"
ordering = "NONE"
side = "BOTH"